language:   generic
sudo: required
services:
    - docker
    
before_install:
    - docker build -t localtag -f Dockerfile.dev .
    
script:
    - docker run -e CI=true localtag npm run test

deploy:
    provider:   elasticbeanstalk
    region:     "ap-southeast-1"
    app:        "docker-react" 
    env:        "DockerReact-env"
    bucket_name:    "elasticbeanstalk-ap-southeast-1-622166184645"
    bucket_path:    "docker-react"
    on:
        branch: master   
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY